<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities [
<!ELEMENT expression (#PCDATA)>
<!ELEMENT maths (#PCDATA | expression | evaluation)*>
<!ELEMENT french (#PCDATA)>
<!ELEMENT entities (#PCDATA | maths | french)*>
<!ELEMENT evaluation (#PCDATA)> ]>

<entities>
    <maths>
        <expression>20 &lt; 50</expression>
        <evaluation>true</evaluation>
    </maths>
    <french>Il nous &#233;tait tr&#232;s agr&#233;able d'aprendre que vous avez les numismatiques, mais il nous fachait bien de en m&#234;me temps, que vous n'en possedez pas une &#233;preuve.</french>
</entities>
