<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities [
<!ELEMENT expression (#PCDATA)>
<!ELEMENT maths (#PCDATA | expression | evaluation)*>
<!ELEMENT french (#PCDATA)>
<!ELEMENT entities (#PCDATA | maths | french)*>
<!ELEMENT evaluation (#PCDATA)>
<!ENTITY eacute "&#233;">
<!ENTITY egrave "&#232;">
<!ENTITY ecirc "&#234;">
]>
<entities>
    <maths>
        <expression>20 &lt; 50</expression>
        <evaluation>true</evaluation>
    </maths>
    <french>Il nous &eacute;tait tr&egrave;s agr&eacute;able d'aprendre que vous avez les numismatiques, mais il nous fachait bien de en m&ecirc;me temps, que vous n'en possedez pas une &eacute;preuve. </french>
</entities>
